### PR TITLE
libnet_ifaddrlist: fix file descriptor leak

### PR DESCRIPTION
**Pull request by cmicali**
libnet_ifaddrlist currently leaks the file descriptor of the socket() that's opened on line 124. When frequently init/destroying libnet this bug causes programs to run out of file descriptors pretty quickly.

This PR closes the fd in regular operation and error cases while attempting to follow the existing code style.

### CODE REVIEW

**Comment by sgeto** [comment]
I have a sort of unrelated question:
in libnet.h `sys/sockio.h` is only included when `SIOCGIFADDR `is not defined, yet this file includes it even when it is. Can you shed some light on that?
Thank you

**Comment by sam-github** [comment]
@sgeto my guess is that it allows the API user to decide whether or from where they want SIOCGIFADDR defined. It doesn't need to be in libnet.h to use  the libnet API. In this file, I assume its actually needed, so its included.

**Comment by sam-github** [comment]
@cmicali Thanks

**Comment by sgeto** [comment]
> It doesn't need to be in libnet.h to use the libnet API.

Yes, makes sense.

"We are saddened by a bird's cry, but not for a fish's blood.
Blessed are those with voices."

-Mamoru Oshii

**Pull request merged**
