### PR TITLE
Cleanup for MSVC+MingW.

### PR DESCRIPTION
**Pull request by gvanem**
Fixed building for MingW+MSVC. Those seems to have fallen behind. Adding a single GNU makefile for both MSVC+MingW soon. Note: a lot of white-space changes. (trailing WS removed).

### CODE REVIEW

**Comment by sgeto** [comment]
This is amazing. A real shame it was never merged.

**Comment by gvanem** [comment]
I forgot about that entirely. I think I just delete this *Pll Request* since Sam seems o have lost interest in libnet...

**Comment by gvanem** [comment]
Closing.

**Comment by sgeto** [comment]
[shamelessly stolen!](https://github.com/sgeto/libnet/commit/51bf711a567f880af3c78783cf80921e6fa14f35)

**Comment by gvanem** [comment]
libnet is a cool library. It should be better maintained.  Maybe you can fork it? Good luck!

**Comment by koeppea** [comment]
Yes I'd also like to see it keeping maintained. :+1

**Comment by sgeto** [comment]
Thanks. I've been thinking for a while to help reviving the project. Here actually with sam and you guys. But things look really abandoned.
I'll do my best maintaining my fork and even out as many bumps as I can. if you even want to help out or contribute in any other way, you can find my fork [here ](https://github.com/sgeto/libnet), Would be cool if you could share some of your brainpower there every now and then. 

Cheers!

**Pull request closed without merging**
