### PR TITLE
_DEFAULT_SOURCE should be used when _BSD_SOURCE

### PR DESCRIPTION
**Pull request by Kokan**
The compiler complains:
```
/usr/include/features.h:184:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
```
Solution: https://stackoverflow.com/a/29201732

### CODE REVIEW

**Comment by sgeto** [comment]
Fine with me.
I don't get these warning though. What's your setup?

**Comment by Kokan** [comment]
The syslog-ng project uses libnet, and when you compile syslog-ng on ubuntu bionic, the following errors appear.

**Comment by koeppea** [comment]
On which platform?

**Comment by Kokan** [comment]
@koeppea I tried only on x86_64.

**Pull request merged**
